{{- if .Values.webhookSigning.generateSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postal-sendgrid.webhookSigningSecretName" . }}
  labels:
    {{- include "postal-sendgrid.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.webhookSigning.privateKeySecretKey }}: {{ genPrivateKey "ecdsa" | quote }}
{{- end }}
